### ISSUE TITLE
Fix Radius passwords

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#15]
Change Radius passwords to the hashed Urán passwords.

**Comment by luksan47** [comment]
Note that this task is different from #16, #15 is should solve some problem in the radius configuration.

**Comment by uno20001** [comment]
In my opinion the easiest way to have synchronized Urán és RADIUS passwords is to make the RADIUS server use an SQL database for authentication (freeRADIUS can do that) (the database can even be on the the same server where the Laravel stuff is stored). On signing-up the user is added to both the radius database and the Laravel database; on changing password the password is changed in both databases. Since, as far as I can see, standard Unix-style "crypt" hashes are used in Urán, the radius synchronization should work without much configuration, I think. We should also note, that only PAP and EAP-GTC support Unix-style hashes, according to [this website](http://deployingradius.com/documents/protocols/compatibility.html).

**Comment by gkrupp** [comment]
How about dropping the FreeRADIUS restrictions and implement a custom RADIUS server,
so we don't have to adapt/puzzle with existing tools and authenticate directly to the main Uran DB?

**Comment by luksan47** [comment]
@gkrupp @hamaren2517 will you have time to work in this before the next semester starts?
