### ISSUE TITLE
Change lang directive to __ function.

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#40]
From the Laravel documentation:

> The @lang directive does not escape any output. You are fully responsible for escaping your own output when using this directive.

We should move to the newer __ helper function.

**Comment by luksan47** [comment]
@vendi95 what do you think?

**Comment by vendi95** [comment]
If I understand properly HTML tags are escaped only. HTML injection is not a real threat to us because of the staticity of the strings. Also, not the __ helper function but the {{ }} operation does the escaping, which is true for every value printing. (The nonescaping version is {!! !!}).
Moreover, it can be useful for us, to include HTML tags in language-dependent strings, for example bold text in the middle.
I recommend using the @lang directive in blade templates in simple cases and the __ helper in pure PHP code.

**Comment by luksan47** [comment]
Thanks for the clarification, we'll follow this advice.
