### ISSUE TITLE
Improve checkout payments

### ISSUE THREAD

**Issue by kdmnk** [luksan47/mars#438]
- In the student council checkout, we need a function to pay to workshops. The workshop's balance should be modified accordingly.
- We need a function to pay / receive money to/from collegists. If we can authorize the transaction by both sides, we will be able to make receipts.
- Paying from the checkout (expenses) and paying to the checkout (incomes) should be seperated.
- We don't want all the transactions to be added to the checkouts straight away. A simple checkbox should be enough for this, and a card like what we use on kkt/netreg page to add the existing transactions to the checkout. 
- Adding existing transactions to the checkout should be able to be initiated by both sides. (We only have it from the collector side - with the checkout manager's password, but the checkout manager should be able to choose a collector who pays to the checkout). We don't need authentication necessarily for this since this is the checkout's manager's responsibility.
- Consider deleting password authentication for adding transactions to the checkouts. We already have an economic committee leader role for this.

**Comment by luksan47** [comment]
#461 is a prerequisite.

**Comment by luksan47** [comment]
Use QR code.

**Comment by luksan47** [comment]
> In the student council checkout, we need a function to pay to workshops. The workshop's balance should be modified accordingly.
I would think here in not just paying, but complete administration for workshop balances. Similar methods could be used when moving collected money to checkout.

> We need a function to pay / receive money to/from collegists. If we can authorize the transaction by both sides, we will be able to make receipts.
Same functionality as move to checkout.

> Adding existing transactions to the checkout should be able to be initiated by both sides. (We only have it from the collector side - with the checkout manager's password, but the checkout manager should be able to choose a collector who pays to the checkout). We don't need authentication necessarily for this since this is the checkout's manager's responsibility.

Regarding this item: we have it for both sides, since only the checkout manager can add them from the collector's page. Maybe a cooler solution would be to use QR codes. When the collector hands over money, a QR code show up that the committee leader can scan. This would automatically collect everything (or if you insist, only checked items).
What could be added here is a page for the committee leader to see who has collected money.

> Consider deleting password authentication for adding transactions to the checkouts. We already have an economic committee leader role for this.

The password field should be removed from here, a simple policy check is enough.

Before anything moves forward here:

1. We need #461 merged.
2. We need to plan this thoroughly to prevent the need for big refactorings.
3. All points here should be a separate issue and a separate PR (depends on the planning). The best might be if everything here will be in one hand, but I insist on small PRs/issues.

**Comment by kdmnk** [comment]
I Consulted with the committe leader. 
The priorities now is to see the money received by committe members that has not been moved to the checkout.

> Adding existing transactions to the checkout should be able to be initiated by both sides. (We only have it from the collector side - with the checkout manager's password, but the checkout manager should be able to choose a collector who pays to the checkout).

This has more sense if the checkout manager can add these transactions, as far as we use the paper receipts (we can omit these later with qr codes for example). This can be done with policies only, and without passwords, so its much more convenient.

I made those changes in the pr above.

The workshop balance system will be modified probably, so we can add more issues once we have the plan for them.
