### ISSUE TITLE
Add permission system

### ISSUE THREAD

**Issue by luksan47** [luksan47/mars#62]
Tenants should be able to print and have access to the internet module.
We should not require information about their studies at the registration.

**Comment by vendi95** [comment]
I think we should implement a more advanced permission system. I am sure, we can find a good existing solution.
Can somebody do the research?

**Comment by uno20001** [comment]
Maybe [laravel-permission](https://github.com/spatie/laravel-permission) could do the job if I'm not misunderstanding anything.

**Comment by luksan47** [comment]
Yeah, it would be nice to define roles as laravel-permission does, looks good to me.

**Comment by uno20001** [comment]
[It doesn't look particularly complicated to install the package.](https://docs.spatie.be/laravel-permission/v3/installation-laravel/)

**Comment by vendi95** [comment]
Szia!
We decided not to go with laravel-permission because of its lack of object dependent permissions. If I am not mistaken, for example, you can not give permission to a user to view a particular uploaded document but not another one.
We are planning to use role-based, manually written laravel gates. For which we need a system for assigning and unassigning roles to users. The roles should be stored in a DB table, but they are static, new roles can be added only with migrations. On the admin UI, users can be assigned/unassigned to these static roles as a many-to-many relationship. (For the UI it would be nice to use the design principles as in the mac-addresses branch.) We need a hasRole function on User instances that we can use in the gates to check if a user has a given role.
What do you think about this @uno20001?

**Comment by uno20001** [comment]
Unfortunately laravel-permission, indeed, doesn't support per object permissions. If I understand everything correctly, then something like [this](https://laravel-news.com/authorization-gates) is the plan, right?

**Comment by luksan47** [comment]
> then something like this is the plan, right?

Right. We are basically done now, only have to configure it.
